# Use AWS Lambda Python base image
FROM amazon/aws-lambda-python:3.10


# Copy requirements file
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Command to run your main script
CMD ["main.lambda_handler"]